# Generated by Django 5.0.6 on 2024-05-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_parent',
        ),
    ]
